DROP TABLE `ITEM_CHARGE_LIST`;
DROP TABLE `TYPE_CHARGE_LIST`;
DROP TABLE `CLOUD_SERVICE_CHARGE_LIST`;
DROP TABLE `THIRD_PARTY_CHARGE_LIST`;
DROP TABLE `MANAGED_SERVICE_LIST`;
DROP TABLE `OTHER_SERVICE_LIST`;
DROP TABLE `TOTAL_CLOUD_CHARGE_LIST`;
DROP TABLE `TOTAL_THIRD_PARTY_CHARGE_LIST`;
DROP TABLE `TOTAL_MANAGED_SERVICE_CHARGE_LIST`;
DROP TABLE `TOTAL_OTHER_SERVICE_CHARGE_LIST`;
DROP TABLE `TOTAL_CHARGE_LIST`;
DROP TABLE `SERVICE_LIST`;
DROP TABLE `CLOUD_LIST`;
DROP TABLE `USER_LIST`;


-- USER_LIST 테이블
CREATE TABLE `USER_LIST` (
    `USER_ID` INT NOT NULL AUTO_INCREMENT,
    `USER_NAME` VARCHAR(50) NULL,
    PRIMARY KEY (`USER_ID`)
);

-- CLOUD_LIST 테이블
CREATE TABLE `CLOUD_LIST` (
    `CLOUD_ID` INT NOT NULL AUTO_INCREMENT,
    `USER_ID` INT NOT NULL,
    `CLOUD_NAME` VARCHAR(50) NULL,
    `CLOUD_CLASS` VARCHAR(50) NULL,
    `CLOUD_KEY` VARCHAR(50) NULL,
    `START_DATE` INT NULL,
    PRIMARY KEY (`CLOUD_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER_LIST`(`USER_ID`)
);

-- SERVICE_LIST 테이블
CREATE TABLE `SERVICE_LIST` (
    `SERVICE_ID` INT NOT NULL AUTO_INCREMENT,
    `CLOUD_ID` INT NOT NULL,
    `SERVICE_NAME` VARCHAR(50) NULL,
    `SERVICE_CODE` VARCHAR(50) NULL,
    PRIMARY KEY (`SERVICE_ID`),
    FOREIGN KEY (`CLOUD_ID`) REFERENCES `CLOUD_LIST`(`CLOUD_ID`)
);

-- TOTAL_CHARGE_LIST 테이블
CREATE TABLE `TOTAL_CHARGE_LIST` (
    `TOTAL_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `CLOUD_ID` INT NOT NULL,
    `BILL_MONTH` INT NULL,
    `TOTAL_USE_AMT` INT DEFAULT 0,
    `TOTAL_DISCOUNT_AMT` INT DEFAULT 0,
    `TOTAL_SALES_DISCOUNT_AMT` INT DEFAULT 0,
    `TOTAL_COIN_USE_AMT` INT DEFAULT 0,
    `TOTAL_DEFAULT_AMT` INT DEFAULT 0,
    `TOTAL_VAT_AMT` INT DEFAULT 0,
    `TOTAL_VAT_INCLUDE_AMT` INT DEFAULT 0,
    `TOTAL_PAY_AMT` INT DEFAULT 0,
    `TOTAL_USER_PAY_AMT` INT DEFAULT 0,
    `TOTAL_DISCOUNT_INCLUDE_AMT` INT DEFAULT 0,
    `TOTAL_USE_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_VAT_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_COIN_USE_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_PAY_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_VAT_INCLUDE_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_SALES_DISCOUNT_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_DISCOUNT_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_DISCOUNT_INCLUDE_NOTES` VARCHAR(50) DEFAULT '',
    `TOTAL_DEFAULT_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`TOTAL_CHARGE_ID`),
    FOREIGN KEY (`CLOUD_ID`) REFERENCES `CLOUD_LIST`(`CLOUD_ID`)
);

-- TOTAL_MANAGED_SERVICE_CHARGE_LIST 테이블
CREATE TABLE `TOTAL_MANAGED_SERVICE_CHARGE_LIST` (
    `TOTAL_MANAGED_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `TOTAL_MANAGED_SERVICE_USE_AMT` INT DEFAULT 0,
    `TOTAL_MANAGED_SERVICE_DISCOUNT_AMT` INT DEFAULT 0,
    `TOTAL_MANAGED_SERVICE_VAT_AMT` INT DEFAULT 0,
    `TOTAL_MANAGED_SERVICE_VAT_INCLUDE_AMT` INT DEFAULT 0,
    `TOTAL_MANAGED_SERVICE_PAY_AMT` INT DEFAULT 0,
    `TOTAL_MANAGED_SERVICE_USER_PAY_AMT` INT DEFAULT 0,
    `TOTAL_MANAGED_SERVICE_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`TOTAL_MANAGED_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);

-- TOTAL_THIRD_PARTY_CHARGE_LIST 테이블
CREATE TABLE `TOTAL_THIRD_PARTY_CHARGE_LIST` (
    `TOTAL_THIRD_PARTY_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `TOTAL_THIRD_PARTY_USE_AMT` INT DEFAULT 0,
    `TOTAL_THIRD_PARTY_DISCOUNT_AMT` INT DEFAULT 0,
    `TOTAL_THIRD_PARTY_VAT_AMT` INT DEFAULT 0,
    `TOTAL_THIRD_PARTY_VAT_INCLUDE_AMT` INT DEFAULT 0,
    `TOTAL_THIRD_PARTY_PAY_AMT` INT DEFAULT 0,
    `TOTAL_THIRD_PARTY_USER_PAY_AMT` INT DEFAULT 0,
    `TOTAL_THIRD_PARTY_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`TOTAL_THIRD_PARTY_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);

-- TOTAL_OTHER_SERVICE_CHARGE_LIST 테이블
CREATE TABLE `TOTAL_OTHER_SERVICE_CHARGE_LIST` (
    `TOTAL_OTHER_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `TOTAL_OTHER_SERVICE_USE_AMT` INT DEFAULT 0,
    `TOTAL_OTHER_SERVICE_DISCOUNT_AMT` INT DEFAULT 0,
    `TOTAL_OTHER_SERVICE_VAT_AMT` INT DEFAULT 0,
    `TOTAL_OTHER_SERVICE_VAT_INCLUDE_AMT` INT DEFAULT 0,
    `TOTAL_OTHER_SERVICE_PAY_AMT` INT DEFAULT 0,
    `TOTAL_OTHER_SERVICE_USER_PAY_AMT` INT DEFAULT 0,
    `TOTAL_OTHER_SERVICE_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`TOTAL_OTHER_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);


-- TOTAL_CLOUD_CHARGE_LIST 테이블
CREATE TABLE `TOTAL_CLOUD_CHARGE_LIST` (
    `TOTAL_CLOUD_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `TOTAL_CLOUD_USE_AMT` INT DEFAULT 0,
    `TOTAL_CLOUD_DISCOUNT_AMT` INT DEFAULT 0,
    `TOTAL_CLOUD_VAT_AMT` INT DEFAULT 0,
    `TOTAL_CLOUD_VAT_INCLUDE_AMT` INT DEFAULT 0,
    `TOTAL_CLOUD_PAY_AMT` INT DEFAULT 0,
    `TOTAL_CLOUD_USER_PAY_AMT` INT DEFAULT 0,
    `TOTAL_CLOUD_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`TOTAL_CLOUD_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);

-- CLOUD_SERVICE_CHARGE_LIST 테이블
CREATE TABLE `CLOUD_SERVICE_CHARGE_LIST` (
    `CLOUD_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CLOUD_CHARGE_ID` INT NOT NULL,
    `CLOUD_SERVICE_CHARGE_NAME` VARCHAR(50) NULL,
    `CLOUD_SERVICE_CHARGE_CODE` VARCHAR(50) NULL,
    `CLOUD_SERVICE_USE_AMT` INT DEFAULT 0,
    `CLOUD_SERVICE_DISCOUNT_AMT` INT DEFAULT 0,
    `CLOUD_SERVICE_PAY_AMT` INT DEFAULT 0,
    `CLOUD_SERVICE_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`CLOUD_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CLOUD_CHARGE_ID`) REFERENCES `TOTAL_CLOUD_CHARGE_LIST`(`TOTAL_CLOUD_CHARGE_ID`)
);

-- TYPE_CHARGE_LIST 테이블
CREATE TABLE `TYPE_CHARGE_LIST` (
    `TYPE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `CLOUD_SERVICE_CHARGE_ID` INT NOT NULL,
    `TYPE_NAME` VARCHAR(50) NULL,
    `TYPE_USE_AMT` INT DEFAULT 0,
    `TYPE_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`TYPE_CHARGE_ID`),
    FOREIGN KEY (`CLOUD_SERVICE_CHARGE_ID`) REFERENCES `CLOUD_SERVICE_CHARGE_LIST`(`CLOUD_SERVICE_CHARGE_ID`)
);

-- ITEM_CHARGE_LIST 테이블
CREATE TABLE `ITEM_CHARGE_LIST` (
    `ITEM_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TYPE_CHARGE_ID` INT NOT NULL,
    `ITEM_NAME` VARCHAR(50) NULL,
    `ITEM_REGION` VARCHAR(50) NULL,
    `ITEM_USE_AMT` INT DEFAULT 0,
    `ITEM_START_DATE` DATETIME NULL,
    `ITEM_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`ITEM_CHARGE_ID`),
    FOREIGN KEY (`TYPE_CHARGE_ID`) REFERENCES `TYPE_CHARGE_LIST`(`TYPE_CHARGE_ID`)
);

-- THIRD_PARTY_CHARGE_LIST 테이블
CREATE TABLE `THIRD_PARTY_CHARGE_LIST` (
    `THIRD_PARTY_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_THIRD_PARTY_CHARGE_ID` INT NOT NULL,
    `THIRD_PARTY_NAME` VARCHAR(50) NULL,
    `THIRD_PARTY_PRODUCT_NAME` VARCHAR(50) NULL,
    `THIRD_PARTY_USE_AMT` INT DEFAULT 0,
    `THIRD_PARTY_PAY_AMT` INT DEFAULT 0,
    `THIRD_PARTY_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`THIRD_PARTY_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_THIRD_PARTY_CHARGE_ID`) REFERENCES `TOTAL_THIRD_PARTY_CHARGE_LIST`(`TOTAL_THIRD_PARTY_CHARGE_ID`)
);

-- MANAGED_SERVICE_LIST 테이블
CREATE TABLE `MANAGED_SERVICE_LIST` (
    `MANAGED_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_MANAGED_SERVICE_CHARGE_ID` INT NOT NULL,
    `MANAGED_SERVICE_NAME` VARCHAR(50) NULL,
    `MANAGED_PRODUCT_NAME` VARCHAR(50) NULL,
    `MANAGED_SERVICE_USE_AMT` INT DEFAULT 0,
    `MANAGED_SERVICE_PAY_AMT` INT DEFAULT 0,
    `MANAGED_SERVICE_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`MANAGED_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_MANAGED_SERVICE_CHARGE_ID`) REFERENCES `TOTAL_MANAGED_SERVICE_CHARGE_LIST`(`TOTAL_MANAGED_SERVICE_CHARGE_ID`)
);

-- OTHER_SERVICE_LIST 테이블
CREATE TABLE `OTHER_SERVICE_LIST` (
    `OTHER_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_OTHER_SERVICE_CHARGE_ID` INT NOT NULL,
    `OTHER_SERVICE_NAME` VARCHAR(50) NULL,
    `OTHER_PRODUCT_NAME` VARCHAR(50) NULL,
    `OTHER_SERVICE_USE_AMT` INT DEFAULT 0,
    `OTHER_SERVICE_PAY_AMT` INT DEFAULT 0,
    `OTHER_SERVICE_NOTES` VARCHAR(50) DEFAULT '',
    PRIMARY KEY (`OTHER_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_OTHER_SERVICE_CHARGE_ID`) REFERENCES `TOTAL_OTHER_SERVICE_CHARGE_LIST`(`TOTAL_OTHER_SERVICE_CHARGE_ID`)
);

