DROP TABLE `ITEM_CHARGE_LIST`;
DROP TABLE `TYPE_CHARGE_LIST`;
DROP TABLE `CLOUD_SERVICE_CHARGE_LIST`;
DROP TABLE `THIRD_PARTY_CHARGE_LIST`;
DROP TABLE `MANAGED_SERVICE_LIST`;
DROP TABLE `OTHER_SERVICE_LIST`;
DROP TABLE `CLOUD_TOTAL_CHARGE_LIST`;
DROP TABLE `SERVICE_LIST`;
DROP TABLE `CLOUD_LIST`;
DROP TABLE `USER_LIST`;

CREATE TABLE `USER_LIST` (
    `USER_ID` INT NOT NULL AUTO_INCREMENT,
    `USER_NAME` VARCHAR(50) NULL,
    PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `CLOUD_LIST` (
    `CLOUD_ID` INT NOT NULL AUTO_INCREMENT,
    `USER_ID` INT NOT NULL,
    `CLOUD_NAME` VARCHAR(50) NULL,
    `CLOUD_CLASS` VARCHAR(50) NULL,
    `CLOUD_KEY` VARCHAR(50) NULL,
    `START_DATE` INT NULL,
    PRIMARY KEY (`CLOUD_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER_LIST`(`USER_ID`)
);

CREATE TABLE `SERVICE_LIST` (
    `SERVICE_ID` INT NOT NULL AUTO_INCREMENT,
    `CLOUD_ID` INT NOT NULL,
    `SERVICE_NAME` VARCHAR(50) NULL,
    `SERVICE_CODE` VARCHAR(50) NULL,
    PRIMARY KEY (`SERVICE_ID`),
    FOREIGN KEY (`CLOUD_ID`) REFERENCES `CLOUD_LIST`(`CLOUD_ID`)
);

CREATE TABLE `CLOUD_TOTAL_CHARGE_LIST` (
    `TOTAL_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `CLOUD_ID` INT NOT NULL,
    `BILL_MONTH` INT NULL,
    `TOTAL_USE_AMT` INT NULL,
    `TOTAL_DISCOUNT_AMT` INT NULL,
    `TOTAL_COIN_USE_AMT` INT NULL,
    `TOTAL_DEFAULT_AMT` INT NULL,
    `TOTAL_VAT_AMT` INT NULL,
    `TOTAL_VAT_INCLUDE_AMT` INT NULL,
    `TOTAL_PAY_AMT` INT NULL,
	`CLOUD_NOTES`	VARCHAR(50)	NULL,
    PRIMARY KEY (`TOTAL_CHARGE_ID`),
    FOREIGN KEY (`CLOUD_ID`) REFERENCES `CLOUD_LIST`(`CLOUD_ID`)
);

CREATE TABLE `CLOUD_SERVICE_CHARGE_LIST` (
    `CLOUD_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `CLOUD_SERVICE_CHARGE_NAME` VARCHAR(50) NULL,
    `CLOUD_SERVICE_CHARGE_CODE` VARCHAR(50) NULL,
    `CLOUD_SERVICE_USE_AMT` INT NULL,
    `CLOUD_SERVICE_DISCOUNT_AMT` INT NULL,
    `CLOUD_SERVICE_PAY_AMT` INT NULL,
	`CLOUD_SERVICE_NOTES`	VARCHAR(50)	NULL,
    PRIMARY KEY (`CLOUD_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `CLOUD_TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);

CREATE TABLE `TYPE_CHARGE_LIST` (
    `TYPE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `CLOUD_SERVICE_CHARGE_ID` INT NOT NULL,
    `TYPE_NAME` VARCHAR(50) NULL,
    `TYPE_USE_AMT` INT NULL,
	`TYPE_NOTES`	VARCHAR(50)	NULL,
    PRIMARY KEY (`TYPE_CHARGE_ID`),
    FOREIGN KEY (`CLOUD_SERVICE_CHARGE_ID`) REFERENCES `CLOUD_SERVICE_CHARGE_LIST`(`CLOUD_SERVICE_CHARGE_ID`)
);

CREATE TABLE `ITEM_CHARGE_LIST` (
    `ITEM_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TYPE_CHARGE_ID` INT NOT NULL,
    `ITEM_NAME` VARCHAR(50) NULL,
    `ITEM_REGION` VARCHAR(50) NULL,
    `ITEM_USE_AMT` INT NULL,
    `ITEM_START_DATE` DATETIME NULL,
	`ITEM_NOTES`	VARCHAR(50)	NULL,
    PRIMARY KEY (`ITEM_CHARGE_ID`),
    FOREIGN KEY (`TYPE_CHARGE_ID`) REFERENCES `TYPE_CHARGE_LIST`(`TYPE_CHARGE_ID`)
);

CREATE TABLE `THIRD_PARTY_CHARGE_LIST` (
    `THIRD_PARTY_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `THIRD_PARTY_SERVICE_NAME` VARCHAR(50) NULL,
    `THIRD_PARTY_PRODUCT_NAME` VARCHAR(50) NULL,
    `THIRD_PARTY_USE_AMT` INT NULL,
    `THIRD_PARTY_PAY_AMT` INT NULL,
	`THIRD_PARTY_NOTES`	VARCHAR(50)	NULL,
    PRIMARY KEY (`THIRD_PARTY_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `CLOUD_TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);

CREATE TABLE `MANAGED_SERVICE_LIST` (
    `MANAGED_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `MANAGED_SERVICE_NAME` VARCHAR(50) NULL,
    `MANAGED_PRODUCT_NAME` VARCHAR(50) NULL,
    `MANAGED_SERVICE_USE_AMT` INT NULL,
    `MANAGED_SERVICE_PAY_AMT` INT NULL,
	`MANAGED_SERVICE_NOTES`	VARCHAR(50)	NULL,
    PRIMARY KEY (`MANAGED_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `CLOUD_TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);

CREATE TABLE `OTHER_SERVICE_LIST` (
    `OTHER_SERVICE_CHARGE_ID` INT NOT NULL AUTO_INCREMENT,
    `TOTAL_CHARGE_ID` INT NOT NULL,
    `OTHER_SERVICE_NAME` VARCHAR(50) NULL,
    `OTHER_PRODUCT_NAME` VARCHAR(50) NULL,
    `OTHER_SERVICE_USE_AMT` INT NULL,
    `OTHER_SERVICE_PAY_AMT` INT NULL,
	`OTHER_SERVICE_NOTES`	VARCHAR(50)	NULL,
    PRIMARY KEY (`OTHER_SERVICE_CHARGE_ID`),
    FOREIGN KEY (`TOTAL_CHARGE_ID`) REFERENCES `CLOUD_TOTAL_CHARGE_LIST`(`TOTAL_CHARGE_ID`)
);
